"use client";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "./supabase";

const Icon=({name,size=21})=>{const p={fill:"none",stroke:"currentColor",strokeWidth:1.9,strokeLinecap:"round",strokeLinejoin:"round"};const d={search:<><circle cx="11" cy="11" r="6.5" {...p}/><path d="m16 16 5 5" {...p}/></>,send:<><path d="M4 4.8 21 11 4 17.2l3.1-5.1L17 11 7.1 9.9Z" {...p}/></>,plus:<><path d="M12 5v14M5 12h14" {...p}/></>,chat:<><path d="M5 5.5h14a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H10l-5 3v-5.1a2 2 0 0 1-2-2v-5.9a2 2 0 0 1 2-2Z" {...p}/></>,logout:<><path d="M10 5H6a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h4M14 8l4 4-4 4M18 12H9" {...p}/></>,back:<path d="m15 5-7 7 7 7" {...p}/>,check:<path d="m6 12 4 4 8-9" {...p}/>,user:<><circle cx="12" cy="8" r="3.5" {...p}/><path d="M5 20c.8-3.4 3.1-5 7-5s6.2 1.6 7 5" {...p}/></>};return <svg width={size} height={size} viewBox="0 0 24 24" aria-hidden>{d[name]}</svg>};

function Auth(){const sb=supabase();const [mode,setMode]=useState("login");const [login,setLogin]=useState("");const [password,setPassword]=useState("");const [username,setUsername]=useState("");const [name,setName]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const submit=async e=>{e.preventDefault();setBusy(true);setError("");try{if(mode==="login"){let {data,error}=await sb.rpc("resolve_login_email",{login_id:login.trim()});if(error)throw error;const email=data||login.trim();const r=await sb.auth.signInWithPassword({email,password});if(r.error)throw r.error}else{if(!username.trim()||!name.trim())throw new Error("نام و نام کاربری را کامل کنید");const email=login.includes("@")?login.trim():`${username.trim().toLowerCase()}@utino.chat`;const r=await sb.auth.signUp({email,password,options:{data:{username:username.trim().toLowerCase(),display_name:name.trim()}}});if(r.error)throw r.error;if(!r.data.session)setError("ثبت‌نام انجام شد. اگر تأیید ایمیل فعال باشد، ایمیل خود را تأیید کنید.")}}catch(x){setError(x.message||"خطای ناشناخته")}finally{setBusy(false)}};
 return <main className="auth"><div className="auth-card"><div className="logo">✈</div><h1>utino chat</h1><p className="muted">پیام‌رسان سریع، ساده و خصوصی</p><form onSubmit={submit}>{mode==="signup"&&<><label>نام نمایشی<input value={name} onChange={e=>setName(e.target.value)} placeholder="مثلاً پرهام" /></label><label>نام کاربری<input value={username} onChange={e=>setUsername(e.target.value.replace(/[^a-zA-Z0-9_]/g,""))} placeholder="username" dir="ltr" /></label></>}<label>{mode==="login"?"ایمیل یا نام کاربری":"ایمیل (اختیاری)"}<input value={login} onChange={e=>setLogin(e.target.value)} placeholder={mode==="login"?"username یا email":"name@example.com"} dir="ltr" required={mode==="login"}/></label><label>رمز عبور<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" minLength={6} required/></label>{error&&<div className="notice">{error}</div>}<button className="primary full" disabled={busy}>{busy?"در حال پردازش…":mode==="login"?"ورود":"ساخت حساب"}</button></form><button className="link" onClick={()=>{setMode(mode==="login"?"signup":"login");setError("")}}>{mode==="login"?"حساب ندارید؟ ثبت‌نام":"حساب دارید؟ ورود"}</button></div></main>}

function Avatar({name}){return <div className="avatar">{(name||"U").trim().slice(0,1).toUpperCase()}</div>}
function Messenger({session}){const sb=supabase();const me=session.user.id;const [profile,setProfile]=useState(null);const [chats,setChats]=useState([]);const [active,setActive]=useState(null);const [messages,setMessages]=useState([]);const [text,setText]=useState("");const [search,setSearch]=useState("");const [results,setResults]=useState([]);const [loading,setLoading]=useState(true);const [mobileChat,setMobileChat]=useState(false);const [error,setError]=useState("");
 const load=async()=>{setLoading(true);const [p,c]=await Promise.all([sb.rpc("get_my_profile"),sb.from("conversation_members").select("conversation_id").eq("user_id",me).is("left_at",null)]);if(!p.error)setProfile(p.data?.[0]||null);if(c.error){setError(c.error.message);setLoading(false);return}const ids=(c.data||[]).map(x=>x.conversation_id);if(!ids.length){setChats([]);setLoading(false);return}const {data,error:e}=await sb.from("conversations").select("id,type,title,created_by,is_channel,description,channel_username,is_public,badge").in("id",ids).order("created_at",{ascending:false});if(e)setError(e.message);else setChats(data||[]);setLoading(false)};
 useEffect(()=>{load();const sub=sb.channel("utino-messages").on("postgres_changes",{event:"INSERT",schema:"public",table:"messages"},payload=>{if(payload.new?.conversation_id===active)setMessages(v=>v.some(x=>x.id===payload.new.id)?v:[...v,payload.new])}).subscribe();return()=>{sb.removeChannel(sub)}},[active]);
 const open=async c=>{setActive(c.id);setMobileChat(true);const {data,error:e}=await sb.from("messages").select("id,sender_id,receiver_id,content,file_url,file_type,file_name,created_at,message_type,edited_at,deleted_at,reactions").eq("conversation_id",c.id).is("deleted_at",null).order("created_at",{ascending:true}).limit(100);if(e)setError(e.message);else setMessages(data||[]);};
 useEffect(()=>{let t;const q=search.trim();if(!q){setResults([]);return}t=setTimeout(async()=>{const {data}=await sb.rpc("search_user_directory",{search_text:q,result_limit:15});setResults((data||[]).filter(x=>x.id!==me))},250);return()=>clearTimeout(t)},[search]);
 const start=async u=>{const {data,error:e}=await sb.rpc("get_or_create_direct_conversation",{other_user_id:u.id});if(e){setError(e.message);return}setSearch("");setResults([]);const c={id:data,type:"direct",title:u.display_name||u.username,is_channel:false};setChats(v=>[c,...v.filter(x=>x.id!==data)]);open(c)};
 const send=async e=>{e?.preventDefault();const value=text.trim();if(!value||!active)return;setText("");const {data,error:e2}=await sb.rpc("send_message",{p_conversation_id:active,p_content:value,p_message_type:"text"});if(e2){setText(value);setError(e2.message);return}if(data){const m={id:data,sender_id:me,content:value,created_at:new Date().toISOString(),message_type:"text"};setMessages(v=>v.some(x=>x.id===data)?v:[...v,m])}};
 const current=chats.find(x=>x.id===active);const title=current?.title||"گفت‌وگو";
 return <div className="app"><aside className={`sidebar ${mobileChat?"hide-mobile":""}`}><header className="side-head"><div><b>utino chat</b><span>{profile?.display_name||profile?.username||""}</span></div><button className="icon-btn" onClick={()=>sb.auth.signOut()} title="خروج"><Icon name="logout"/></button></header><div className="search"><Icon name="search" size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="جستجو" /></div>{results.length>0&&<div className="results">{results.map(u=><button key={u.id} onClick={()=>start(u)}><Avatar name={u.display_name}/><div><b>{u.display_name}</b><small>@{u.username}</small></div></button>)}</div>}<div className="chat-list">{loading?<div className="empty">در حال بارگذاری…</div>:chats.map(c=><button className={`chat-row ${active===c.id?"selected":""}`} key={c.id} onClick={()=>open(c)}><Avatar name={c.title}/><div><b>{c.title||"گفت‌وگو"}</b><small>{c.is_channel?"کانال":"گفت‌وگوی خصوصی"}</small></div></button>)}{!chats.length&&!loading&&<div className="empty">هنوز گفت‌وگویی ندارید.<br/>از جستجو یک کاربر را پیدا کنید.</div>}</div></aside><section className={`conversation ${mobileChat?"show-mobile":""}`}>{current?<><header className="conv-head"><button className="back icon-btn" onClick={()=>setMobileChat(false)}><Icon name="back"/></button><Avatar name={title}/><div><b>{title}</b><small>{current.is_channel?"کانال":"آنلاین"}</small></div></header><div className="messages">{messages.map(m=><div key={m.id} className={`bubble ${m.sender_id===me?"mine":""}`}><div>{m.content}</div><time>{new Date(m.created_at).toLocaleTimeString("fa-IR",{hour:"2-digit",minute:"2-digit"})}{m.sender_id===me&&<Icon name="check" size={14}/>}</time></div>)}</div><form className="composer" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="پیام…" autoComplete="off"/><button className="send" disabled={!text.trim()}><Icon name="send"/></button></form></>:<div className="welcome"><div className="welcome-logo">✈</div><h2>utino chat</h2><p>یک گفت‌وگو را انتخاب کنید یا کاربر جدیدی پیدا کنید.</p></div>}</section>{error&&<button className="error-toast" onClick={()=>setError("")}>{error} ×</button>}</div>}

export default function Home(){const sb=supabase();const [session,setSession]=useState(undefined);useEffect(()=>{sb.auth.getSession().then(({data})=>setSession(data.session));const {data}=sb.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);if(session===undefined)return <main className="loading-screen">utino chat</main>;return session?<Messenger session={session}/>:<Auth/>}